spring.datasource.readonly.url=jdbc:mysql://localhost:3306/workshopdb?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.readonly.username=root
spring.datasource.readonly.password=${DB_PASSWORD}
